### PR TITLE
Uploaded first draft of DatabaseConnection class

### PR DESCRIPTION
**Pull request by scritty1249**
This class is meant to handle all generic interactions between the database and server. Since this draft was made before the database, after the database is made this draft should be tested again, should it be approved.

### CODE REVIEW

**Review by W-Sammy — APPROVED** [review]
LGTM.

**Comment by scritty1249** [comment]
This pull request needs to be edited / taken down once we agree to the new directory structure, as the upload location is no longer legal.

**Comment by W-Sammy** [comment]
Directory structure has been changed, therefore dismissing this PR

**Comment by erdsmabilog** [comment]
Just to have it on here officially:

// I believe its set this way
// NOTE: database and table names aren't case-sensitive for MySQL (scheduledSmiles -> scheduledsmiles)
databaseUrl = "jdbc:mysql://localhost:3306/ScheduledSmiles"

BTW, wanted to ask earlier, but just needed a refresher on my end -- are we giving root access? As in, is "admin" "root" or is it just another user in the system with special perms?

// unsure on this
private String databaseUsername = "root";

I also don't normally see constructors calling basic function setters (unless its from a superclass), but that's more of just my view on it.

// funny names for error (unless that's an actual error name) -- not sure if we're all agreeing to it but I personally like it 

// should we also have an openTransaction

// should we call getters for the getConnection function -- if not, when will they be used?
    public void connect() {
    [...]
    DriverManager.getConnection(
            this.databaseUrl,
            this.databaseUsername,
            this.databasePassword
            );

// could be completely wrong here, but from what I remember, anything after the "//" could change right? although 3306 is set aside typically for localhost -- also added databse name
    public void setUrl(String url) {
        this.databaseUrl = "jdbc:mysql:// " + url + ":3306" + "/ScheduledSmiles;
    }

**Pull request closed without merging**
